package cn.zskxt.entity;

public class zsk_book_content {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_content.id
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_content.content
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_content.id
     *
     * @return the value of zsk_book_content.id
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_content.id
     *
     * @param id the value for zsk_book_content.id
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_content.content
     *
     * @return the value of zsk_book_content.content
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_content.content
     *
     * @param content the value for zsk_book_content.content
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}