package cn.zskxt.entity;

import java.util.Date;

public class zsk_book_sm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_sm.bookid
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private String bookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_sm.bookname
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private String bookname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_sm.zz
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private String zz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_sm.zhgxsj
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private Date zhgxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_sm.tp
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private String tp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_sm.zxzj
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private String zxzj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_sm.zxzjid
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private String zxzjid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_sm.msnr
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private String msnr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_sm.lb
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private String lb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_sm.bookid
     *
     * @return the value of zsk_book_sm.bookid
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public String getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_sm.bookid
     *
     * @param bookid the value for zsk_book_sm.bookid
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setBookid(String bookid) {
        this.bookid = bookid == null ? null : bookid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_sm.bookname
     *
     * @return the value of zsk_book_sm.bookname
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_sm.bookname
     *
     * @param bookname the value for zsk_book_sm.bookname
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_sm.zz
     *
     * @return the value of zsk_book_sm.zz
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public String getZz() {
        return zz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_sm.zz
     *
     * @param zz the value for zsk_book_sm.zz
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setZz(String zz) {
        this.zz = zz == null ? null : zz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_sm.zhgxsj
     *
     * @return the value of zsk_book_sm.zhgxsj
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public Date getZhgxsj() {
        return zhgxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_sm.zhgxsj
     *
     * @param zhgxsj the value for zsk_book_sm.zhgxsj
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setZhgxsj(Date zhgxsj) {
        this.zhgxsj = zhgxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_sm.tp
     *
     * @return the value of zsk_book_sm.tp
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public String getTp() {
        return tp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_sm.tp
     *
     * @param tp the value for zsk_book_sm.tp
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setTp(String tp) {
        this.tp = tp == null ? null : tp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_sm.zxzj
     *
     * @return the value of zsk_book_sm.zxzj
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public String getZxzj() {
        return zxzj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_sm.zxzj
     *
     * @param zxzj the value for zsk_book_sm.zxzj
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setZxzj(String zxzj) {
        this.zxzj = zxzj == null ? null : zxzj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_sm.zxzjid
     *
     * @return the value of zsk_book_sm.zxzjid
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public String getZxzjid() {
        return zxzjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_sm.zxzjid
     *
     * @param zxzjid the value for zsk_book_sm.zxzjid
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setZxzjid(String zxzjid) {
        this.zxzjid = zxzjid == null ? null : zxzjid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_sm.msnr
     *
     * @return the value of zsk_book_sm.msnr
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public String getMsnr() {
        return msnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_sm.msnr
     *
     * @param msnr the value for zsk_book_sm.msnr
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setMsnr(String msnr) {
        this.msnr = msnr == null ? null : msnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_sm.lb
     *
     * @return the value of zsk_book_sm.lb
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public String getLb() {
        return lb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_sm.lb
     *
     * @param lb the value for zsk_book_sm.lb
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setLb(String lb) {
        this.lb = lb == null ? null : lb.trim();
    }
}