package cn.zskxt.entity;

import java.util.Date;

public class zsk_book_ml {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_ml.mlid
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private String mlid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_ml.zjmc
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private String zjmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_ml.bookid
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private String bookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_ml.content_id
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private String contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_ml.is_delete
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_ml.words
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private Integer words;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_ml.ctime
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zsk_book_ml.mtime
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    private Date mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_ml.mlid
     *
     * @return the value of zsk_book_ml.mlid
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public String getMlid() {
        return mlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_ml.mlid
     *
     * @param mlid the value for zsk_book_ml.mlid
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setMlid(String mlid) {
        this.mlid = mlid == null ? null : mlid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_ml.zjmc
     *
     * @return the value of zsk_book_ml.zjmc
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public String getZjmc() {
        return zjmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_ml.zjmc
     *
     * @param zjmc the value for zsk_book_ml.zjmc
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setZjmc(String zjmc) {
        this.zjmc = zjmc == null ? null : zjmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_ml.bookid
     *
     * @return the value of zsk_book_ml.bookid
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public String getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_ml.bookid
     *
     * @param bookid the value for zsk_book_ml.bookid
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setBookid(String bookid) {
        this.bookid = bookid == null ? null : bookid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_ml.content_id
     *
     * @return the value of zsk_book_ml.content_id
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public String getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_ml.content_id
     *
     * @param contentId the value for zsk_book_ml.content_id
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setContentId(String contentId) {
        this.contentId = contentId == null ? null : contentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_ml.is_delete
     *
     * @return the value of zsk_book_ml.is_delete
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_ml.is_delete
     *
     * @param isDelete the value for zsk_book_ml.is_delete
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_ml.words
     *
     * @return the value of zsk_book_ml.words
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public Integer getWords() {
        return words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_ml.words
     *
     * @param words the value for zsk_book_ml.words
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setWords(Integer words) {
        this.words = words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_ml.ctime
     *
     * @return the value of zsk_book_ml.ctime
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_ml.ctime
     *
     * @param ctime the value for zsk_book_ml.ctime
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zsk_book_ml.mtime
     *
     * @return the value of zsk_book_ml.mtime
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zsk_book_ml.mtime
     *
     * @param mtime the value for zsk_book_ml.mtime
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
}