package cn.zskxt.dao;

import cn.zskxt.entity.zsk_book_sm;
import java.util.List;

public interface zsk_book_smMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zsk_book_sm
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    int deleteByPrimaryKey(String bookid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zsk_book_sm
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    int insert(zsk_book_sm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zsk_book_sm
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    zsk_book_sm selectByPrimaryKey(String bookid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zsk_book_sm
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    List<zsk_book_sm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zsk_book_sm
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    int updateByPrimaryKey(zsk_book_sm record);
}