package cn.zskxt.dao;

import cn.zskxt.entity.zsk_book_ml;
import java.util.List;

public interface zsk_book_mlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zsk_book_ml
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    int deleteByPrimaryKey(String mlid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zsk_book_ml
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    int insert(zsk_book_ml record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zsk_book_ml
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    zsk_book_ml selectByPrimaryKey(String mlid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zsk_book_ml
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    List<zsk_book_ml> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zsk_book_ml
     *
     * @mbggenerated Thu Oct 17 10:07:54 CST 2019
     */
    int updateByPrimaryKey(zsk_book_ml record);
}